# **Pytorch**

In [ ]:
import numpy as np
import torch

In [ ]:
#initializing a numpy array
a = np.array(1)
#initializing a tensor
b = torch.tensor([[1,3],[1,2]])

print(a)
print(type(a))
print(b)
print(b[1][0].item())
print(type(b))

1
<class 'numpy.ndarray'>
tensor([[1, 3],
        [1, 2]])
1
<class 'torch.Tensor'>


In [ ]:
a = np.array([1,3])
b = np.array([2,4])
print(a,b)
print(a+b)
print(a-b)
print(a/b)
print(a@b)

[1 3] [2 4]
[3 7]
[-1 -1]
[0.5  0.75]
14


In [ ]:
a = np.array([[1,3,1],[10,2,4],[1,4,2]])
b = np.array([[1,3,2],[10,12,4],[1,4,6]])
print(a,b)
print(a+b)
print(a-b)
print(a/b)
print(a@b)

[[ 1  3  1]
 [10  2  4]
 [ 1  4  2]] [[ 1  3  2]
 [10 12  4]
 [ 1  4  6]]
[[ 2  6  3]
 [20 14  8]
 [ 2  8  8]]
[[  0   0  -1]
 [  0 -10   0]
 [  0   0  -4]]
[[1.         1.         0.5       ]
 [1.         0.16666667 1.        ]
 [1.         1.         0.33333333]]
[[32 43 20]
 [34 70 52]
 [43 59 30]]


In [ ]:
a = torch.tensor([[1,3,1],[10,2,4],[1,4,2]])
b = torch.tensor([[1,3,2],[10,12,4],[1,4,6]])
print(a,b)
print(a+b)
print(a-b)
print(a/b)
print(a@b)

tensor([[ 1,  3,  1],
        [10,  2,  4],
        [ 1,  4,  2]]) tensor([[ 1,  3,  2],
        [10, 12,  4],
        [ 1,  4,  6]])
tensor([[ 2,  6,  3],
        [20, 14,  8],
        [ 2,  8,  8]])
tensor([[  0,   0,  -1],
        [  0, -10,   0],
        [  0,   0,  -4]])
tensor([[1.0000, 1.0000, 0.5000],
        [1.0000, 0.1667, 1.0000],
        [1.0000, 1.0000, 0.3333]])
tensor([[32, 43, 20],
        [34, 70, 52],
        [43, 59, 30]])


In [ ]:
torch.manual_seed(7)
a = torch.randn(3,3)
b = torch.randn(3,3)
print('A\n',a,'\n')
print('B\n',b,'\n')

A
 tensor([[-0.1468,  0.7861,  0.9468],
        [-1.1143,  1.6908, -0.8948],
        [-0.3556,  1.2324,  0.1382]]) 

B
 tensor([[-1.6822,  0.3177,  0.1328],
        [ 0.1373,  0.2405,  1.3955],
        [ 1.3470,  2.4382,  0.2028]]) 



In [ ]:
print(torch.add(a,b),'\n')
print(torch.cat((a,b),dim=1))
print(torch.cat((a,b),dim=0))

tensor([[-1.8290,  1.1038,  1.0796],
        [-0.9770,  1.9313,  0.5006],
        [ 0.9914,  3.6706,  0.3409]]) 

tensor([[-0.1468,  0.7861,  0.9468, -1.6822,  0.3177,  0.1328],
        [-1.1143,  1.6908, -0.8948,  0.1373,  0.2405,  1.3955],
        [-0.3556,  1.2324,  0.1382,  1.3470,  2.4382,  0.2028]])
tensor([[-0.1468,  0.7861,  0.9468],
        [-1.1143,  1.6908, -0.8948],
        [-0.3556,  1.2324,  0.1382],
        [-1.6822,  0.3177,  0.1328],
        [ 0.1373,  0.2405,  1.3955],
        [ 1.3470,  2.4382,  0.2028]])


In [ ]:
a = torch.ones((2,2),requires_grad=True)
b = a+5
c = b.mean()
print('A',a)
print('B',b)
print('C',c)

A tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
B tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
C tensor(6., grad_fn=<MeanBackward0>)


In [ ]:
#Backward propagation
c.backward()
#Computing gradient
print('By how much we a values of A\n',a.grad)
print('A\n',a,'\n')

By how much we a values of A
 tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
A
 tensor([[1., 1.],
        [1., 1.]], requires_grad=True) 



In [ ]:
d = a-0.01*a.grad

In [ ]:
d

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<SubBackward0>)

In [ ]:
a.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

# **Multi Layer Perceptron**

In [ ]:
#XNOR GATE using neural networks
import torch
x = [[0,0],
     [0,1],
     [1,0],
     [1,1]]


# **Artificial Neural Network (ANN)**

In [ ]:
x1 = list(range(1,101))
y1 = list(range(5,501,5))
x1 = torch.FloatTensor(x1)
y = torch.FloatTensor(y1)

## Loss Function
def MSE(pred,gt):
  loss = (pred-gt)**2
  loss = (loss.mean()).sum()
  return loss

torch.manual_seed(8)
w1 = torch.randn(1,dtype=torch.float32,requires_grad=True)
w0 = torch.randn(1,dtype=torch.float32,requires_grad=True)
optimizer = torch.optim.SGD([w1,w0], lr = 0.0001)

alpha = 0.00001
for i in range(5000):
  y1 = x1*w1+w0
  loss = MSE(y1,y)
  optimizer.zero_grad() #flushing the gradient every epoch
  loss.backward()
  optimizer.step()
  print("Epoch %d, Loss %f"%(i,loss.item()),end="\r")

print("\n\n Estimated parameters W1: {} W0(bias): {}".format(w1.item(),w0.item()))
in1=int(input())
out=in1*w1+w0
print(out)

Epoch 4999, Loss 0.217492

 Estimated parameters W1: 5.014026641845703 W0(bias): -0.9397153258323669
150
tensor([751.1643], grad_fn=<AddBackward0>)
